### ISSUE TITLE
Seek behavior difference with std

### ISSUE THREAD

**Issue by astarivi** [alemigo/splitfile-rs#1]
`splitfile-rs` seek behavior differs from the std File implementation of seek; seeking out of bounds with the former will be prevented by this [guard](https://github.com/alemigo/splitfile-rs/blob/d45e547b134919a68f3af8c9d3d426aee2044f3a/src/lib.rs#L406C1-L406C72), so it will only seek to the end of the last volume, last file. With std File, seeking out of bounds will pad the file with zeroes up to the requested position.

By removing the guard clause from `splitfile-rs` altogether, it will work exactly like std File does. Due to this difference, SplitFile doesn't act like a drop-in replacement for File in some scenarios. To handle that case, perhaps creating new volumes if the pointer goes over the size of a full volume would be best.

Could this guarding behavior be removed, or perhaps deactivated with a builder parameter?

**Comment by alemigo** [comment]
I agree - it should map against the same behavior as std File.  I believe std File only pads with zeros if an actual write happens, not as a result of the seek itself.  Will verify and change this.

**Comment by alemigo** [comment]
implemented this in latest commit - have a look

**Comment by astarivi** [comment]
It's all working as intended now; tested with multiple kinds of image formats and I got perfect outputs every single time. If possible, please push the update to crates.io to include the updated version in my workflow. Thank you!

**Comment by alemigo** [comment]
published v0.2 on crates.io
